#pragma once
#include <Windows.h>
#include <map>

using namespace std;

class Keys
{
public:

	map<int, string> Map = {
	{ VK_ADD, "[Numpad +]" },
	{ VK_ATTN, "[Attn]" },
	{ VK_BACK, "[Backspace]" },
	{ VK_CANCEL, "[Break]" },
	{ VK_SHIFT, "[Shift]"},
	{ VK_CONTROL, "[Control]"},
	{ VK_TAB, "[Tab]"},
	{ VK_CLEAR, "[Clear]" },
	{ VK_MENU, "[Alt]"},
	{ VK_CRSEL, "[Cr Sel]" },
	{ VK_DECIMAL, "[Numpad .]" },
	{ VK_DIVIDE, "[Numpad /]" },
	{ VK_EREOF, "[Er Eof]" },
	{ VK_ESCAPE, "[Esc]" },
	{ VK_EXECUTE, "[Execute]" },
	{ VK_EXSEL, "[Ex Sel]" },
	{ VK_ICO_CLEAR, "[IcoClr]" },
	{ VK_ICO_HELP, "[IcoHlp]" },
	{ VK_MULTIPLY, "[Numpad *]" },
	{ VK_NONAME, "[NoName]" },
	{ VK_NUMPAD0, "[N0]" },
	{ VK_NUMPAD1, "[N1]" },
	{ VK_NUMPAD2, "[N2]" },
	{ VK_NUMPAD3, "[N3]" },
	{ VK_NUMPAD4, "[N4]" },
	{ VK_NUMPAD5, "[N5]" },
	{ VK_NUMPAD6, "[N6]" },
	{ VK_NUMPAD7, "[N7]" },
	{ VK_NUMPAD8, "[N8]" },
	{ VK_NUMPAD9, "[N9]" },
	{ VK_OEM_1, "[OEM_1 (: ;)]" },
	{ VK_OEM_102, "[OEM_102 (> <)]" },
	{ VK_OEM_2, "[OEM_2 (? /)]" },
	{ VK_OEM_3, "[OEM_3 (~ `)]" },
	{ VK_OEM_4, "[OEM_4 ({ [)]" },
	{ VK_OEM_5, "[OEM_5 (| \\)]" },
	{ VK_OEM_6, "[OEM_6 (} ])]" },
	{ VK_OEM_7, "[OEM_7 (\" \')]" },
	{ VK_OEM_8, "[OEM_8 (: !)]" },
	{ VK_OEM_ATTN, "[Oem Attn]" },
	{ VK_OEM_AUTO, "[AUTO]" },
	{ VK_OEM_AX, "[Ax]" },
	{ VK_OEM_BACKTAB, "[Back Tab]" },
	{ VK_OEM_CLEAR, "[OemClr]" },
	{ VK_OEM_COMMA, "[OEM_COMMA (< ,)]" },
	{ VK_OEM_COPY, "[Copy]" },
	{ VK_OEM_CUSEL, "[Cu Sel]" },
	{ VK_OEM_ENLW, "[Enlw]" },
	{ VK_OEM_FINISH, "[Finish]" },
	{ VK_OEM_FJ_LOYA, "[Loya]" },
	{ VK_OEM_FJ_MASSHOU, "[Mashu]" },
	{ VK_OEM_FJ_ROYA, "[Roya]" },
	{ VK_OEM_FJ_TOUROKU, "[Touroku]" },
	{ VK_OEM_JUMP, "[Jump]" },
	{ VK_OEM_MINUS, "[OEM_MINUS (_ -)]" },
	{ VK_OEM_PA1, "[OemPa1]" },
	{ VK_OEM_PA2, "[OemPa2]" },
	{ VK_OEM_PA3, "[OemPa3]" },
	{ VK_OEM_PERIOD, "[OEM_PERIOD (> .)]" },
	{ VK_OEM_PLUS, "[OEM_PLUS (+ =)]" },
	{ VK_OEM_RESET, "[Reset]" },
	{ VK_OEM_WSCTRL, "WsCtrl]" },
	{ VK_PA1, "[Pa1]" },
	{ VK_PACKET, "[Packet]" },
	{ VK_PLAY, "[Play]" },
	{ VK_PROCESSKEY, "[Process]" },
	{ VK_RETURN, "[Enter]" },
	{ VK_SELECT, "[Select]" },
	{ VK_SEPARATOR, "[Separator]" },
	{ VK_SPACE, " " },
	{ VK_SUBTRACT, "[Num -]" },
	{ VK_TAB, "[Tab]" },
	{ VK_ZOOM, "[Zoom]" },
	{ VK_ACCEPT, "[Accept]" },
	{ VK_APPS, "[Context Menu]" },
	{ VK_BROWSER_BACK, "[Browser Back]" },
	{ VK_BROWSER_FAVORITES, "[Browser Favorites]" },
	{ VK_BROWSER_FORWARD, "[Browser Forward]" },
	{ VK_BROWSER_HOME, "[Browser Home]" },
	{ VK_CAPITAL, "[Caps Lock]" },
	{ VK_CONVERT, "[Convert]" },
	{ VK_DELETE, "[Delete]" },
	{ VK_DOWN, "[Arrow Down]" },
	{ VK_END, "[End]" },
	{ VK_F1, "[F1]" },
	{ VK_F2, "[F2]" },
	{ VK_F3, "[F3]" },
	{ VK_F4, "[F4]" },
	{ VK_F5, "[F5]" },
	{ VK_F6, "[F6]" },
	{ VK_F7, "[F7]" },
	{ VK_F8, "[F8]" },
	{ VK_F9, "[F9]" },
	{ VK_F10, "[F10]" },
	{ VK_F11, "[F11]" },
	{ VK_F12, "[F12]" },
	{ VK_F13, "[F13]" },
	{ VK_F14, "[F14]" },
	{ VK_F15, "[F15]" },
	{ VK_F16, "[F16]" },
	{ VK_F17, "[F17]" },
	{ VK_F18, "[F18]" },
	{ VK_F19, "[F19]" },
	{ VK_F20, "[F20]" },
	{ VK_F21, "[F21]" },
	{ VK_F22, "[F22]" },
	{ VK_F23, "[F23]" },
	{ VK_F24, "[F24]" },
	{ VK_FINAL, "[Final]" },
	{ VK_HELP, "[Help]" },
	{ VK_HOME, "[Home]" },
	{ VK_ICO_00, "[Ico00]" },
	{ VK_INSERT, "[Insert]" },
	{ VK_JUNJA, "[Junja]" },
	{ VK_KANA, "[Kana]" },
	{ VK_KANJI, "[Kanji]" },
	{ VK_LAUNCH_APP1, "[App1]" },
	{ VK_LAUNCH_APP2, "[App2]" },
	{ VK_LAUNCH_MAIL, "[Mail]" },
	{ VK_LAUNCH_MEDIA_SELECT, "[Media]" },
	{ VK_LBUTTON, "[Left Button]" },
	{ VK_LCONTROL, "[Left Ctrl]" },
	{ VK_LEFT, "[Arrow Left]" },
	{ VK_LMENU, "[Left Alt]" },
	{ VK_LSHIFT, "[Left Shift]" },
	{ VK_LWIN, "[Left Win]" },
	{ VK_MBUTTON, "[Middle Button]" },
	{ VK_MEDIA_NEXT_TRACK, "[Next Track]" },
	{ VK_MEDIA_PLAY_PAUSE, "[Play / Pause]" },
	{ VK_MEDIA_PREV_TRACK, "[Previous Track]" },
	{ VK_MEDIA_STOP, "[Stop]" },
	{ VK_MODECHANGE, "[Mode Change]" },
	{ VK_NEXT, "[Page Down]" },
	{ VK_NONCONVERT, "[Non Convert]" },
	{ VK_NUMLOCK, "[Num Lock]" },
	{ VK_OEM_FJ_JISHO, "[Jisho]" },
	{ VK_PAUSE, "[Pause]" },
	{ VK_PRINT, "[Print]" },
	{ VK_PRIOR, "[Page Up]" },
	{ VK_RBUTTON, "[Right Button]" },
	{ VK_RCONTROL, "[Right Ctrl]" },
	{ VK_RIGHT, "[Arrow Right]" },
	{ VK_RMENU, "[Right Alt]" },
	{ VK_RSHIFT, "[Right Shift]" },
	{ VK_RWIN, "[Right Win]" },
	{ VK_SCROLL, "[Scroll Lock]" },
	{ VK_SLEEP, "[Sleep]" },
	{ VK_SNAPSHOT, "[Print Screen]" },
	{ VK_UP, "[Arrow Up]" },
	{ VK_VOLUME_DOWN, "[Volume Down]" },
	{ VK_VOLUME_MUTE, "[Volume Mute]" },
	{ VK_VOLUME_UP, "[Volume Up]" },
	{ VK_XBUTTON1, "[X Button 1]" },
	{ VK_XBUTTON2, "[X Button 2]" }
    };
};